### ISSUE TITLE
Create a dynamic type programmatically

### ISSUE THREAD

**Issue by benkio** [nakamura-to/Soma#4]
Hi
I have some trouble to create a dynamic type for my unit test project in f# because i have some function that get this type as parameter.
Have you some suggestion?
Thx

**Comment by nakamura-to** [comment]
Hi
Could you give me sample code ?
I would like to know more about your trouble.

**Comment by benkio** [comment]
Of course,
I want to test this simple function: 
```F#
let manageSuccess (successResult, message: List<string>) = 
        { ReturnType.Return = true
          ReturnType.Message = "some message... " + ( if (message.IsEmpty) then "" else message |> List.reduce (+))
          ReturnType.UserID = successResult?ATTRIBUTETYPE1
          ReturnType.UserRole = successResult?ATTRIBUTETYPE2 }
```
where: ReturnType is a simple record type, and successResult is a dynamic type from Soma after a join query.
I want to ask you, how i can programmatically create a dynamic type, in order to create a unit test for that function? In particular i don't want to map the join query result as a new type in my project, as i did with regular tables and views, but, if you say that is impossible to create a dynamic type without call the Soma library, i will follow this way to solve this problem. Maybe if i can create a fake type that match the dynamic type in my unit test project then it would be a good workaround.

Thanks for your support and work,
it helps me very much

**Comment by nakamura-to** [comment]
Thank you for your explanation.

Try to use the [dynamic function](https://github.com/nakamura-to/Soma/blob/1.8.0.7/Soma.Core/Db.fs#L1938) as follows.

```fs
open Soma.Core

type ReturnType = { Return : bool; Message : string; UserID : int; UserRole : string }

let manageSuccess (successResult, message: List<string>) = 
    { ReturnType.Return = true
      ReturnType.Message = "some message... " + ( if (message.IsEmpty) then "" else message |> List.reduce (+))
      ReturnType.UserID = successResult?ATTRIBUTETYPE1
      ReturnType.UserRole = successResult?ATTRIBUTETYPE2 }

[<EntryPoint>]
let main argv = 
    // create a dynamic type
    let successResult = dynamic (MsSqlDialect())
    successResult?ATTRIBUTETYPE1 <- 99
    successResult?ATTRIBUTETYPE2 <- "admin"
    // use the dynamic type
    let returnType = manageSuccess (successResult, [])
    printfn "%A" returnType
    0
```

Or if you don't want to depend Soma library, use IDictionary  instead of dynamic type.  Because Soma dynamic type can be treated as IDictionary.

```fs
open System.Collections

let (?) (dynamic:IDictionary) (propName:string) :'a =
    dynamic.[propName] :?> 'a

let inline (?<-) (dynamic:IDictionary) (propName:string) (value:'a) =
    dynamic.[propName] <- value

type ReturnType = { Return : bool; Message : string; UserID : int; UserRole : string }

let manageSuccess (successResult, message: List<string>) = 
    { ReturnType.Return = true
      ReturnType.Message = "some message... " + ( if (message.IsEmpty) then "" else message |> List.reduce (+))
      ReturnType.UserID = successResult?ATTRIBUTETYPE1
      ReturnType.UserRole = successResult?ATTRIBUTETYPE2 }

[<EntryPoint>]
let main argv = 
    // create a Hashtable
    let successResult = Hashtable()
    successResult?ATTRIBUTETYPE1 <- 99
    successResult?ATTRIBUTETYPE2 <- "admin"
    // use the Hashtable
    let returnType = manageSuccess (successResult, [])
    printfn "%A" returnType
    0
```

**Comment by benkio** [comment]
Awesome,
thank you :+1:
