### ISSUE TITLE
How execute raw sql?

### ISSUE THREAD

**Issue by mamcx** [nakamura-to/Soma#7]
I try to send a FULL sql file to create a sqlite database, tables, etc. but look like the library try to parse some things, instead of send the full sql as is:

    Db.execute config sql

    Tests/A simple test: Exception: Soma.Core.SqlException: [SOMA2008] A test data literal or a left parenthesis must be placed right after the bind variable comment(Foreign keys). sql:[ PRAGMA user_version = 1; --Not change this file!!!

    CREATE TABLE SyncLog (
      Id           varchar PRIMARY KEY,
      Name         varchar NOT NULL,
      Op           integer NOT NULL --0 Insert, 1-Update, 2-Delete
    );
    .....
    .....
    .....

**Comment by nakamura-to** [comment]
It seems that your sql file contains some sql comments such as  `/* ... */`.
In Some, such comments have special meanings.
To avoid it, try to use `/** ... */` instead of  `/* ... */` as sql comments.
In other word, use Java documentation comment style.
