### ISSUE TITLE
Reviving the project

### ISSUE THREAD

**Issue by xavierzwirtz** [nakamura-to/Soma#9]
I would like to push this project as the best in class ORM solution for F#. I't needs some heavy refreshing to make that happen though. Part of this would be getting it accepted into the list of F# projects at [FsProjects](http://fsprojects.github.io/). 

I would like to rename the project to FSharp.ORM as well, to better fit the naming scheme that most projects in FsProjects use.

Would I have your blessing @nakamura-to to either become a maintainer or fork the project?

**Comment by nakamura-to** [comment]
That's a great idea. Thank you for asking.

I'm afraid to say, I use this project too heavy to revive it.

Please fork the project freely !

**Comment by xavierzwirtz** [comment]
Thanks for your blessing, I started the fork [here](https://github.com/xavierzwirtz/FSharp.ORM) if you'd like to take a perusal. Your copyright has been preserved on all files.

**Comment by nakamura-to** [comment]
Thank you for your respect to this project.
Best wishes to you !

**Comment by xavierzwirtz** [comment]
No problem, thanks for releasing your code as open source.
